# Generated by Django 5.2.13 on 2026-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
