# Generated by Django 5.2.13 on 2026-04-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resume_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True)),
                ('framework', models.CharField(choices=[('none', 'None'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap')], default='none', max_length=20)),
                ('paper_size', models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal'), ('a5', 'A5')], default='a4', max_length=20)),
                ('preview_image', models.ImageField(blank=True, upload_to='template_previews/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on browse page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
